msgbox"Hi bro",16,"Hello mazafaka"
msgbox"Did you invite me to this pc?",32+4,"Question"
msgbox"Ok, you sure?",64,"Ok"
msgbox"Delete windows?",32+4,"Question"
msgbox"Ok, do you agree?",64,"OK"
msgbox"Deleting...",64,"OK "
msgbox"It was joke",64,"I jocked"
msgbox"Or...",64,"..."